name: scons
on: [push, pull_request]
jobs:
  scons: 
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install scons
        run: pip install scons
      - name: Install gettext
        run: sudo apt-get install gettext
      - name: Generating Addon
        run: scons
      - name: Upload artifact
        uses: actions/upload-artifact@v2-preview
        with:
          path: ./*.nvda-addon